### ISSUE TITLE
Gelfand representation confusion

### ISSUE THREAD

**Issue by khoek** [semorrison/category-theory-2018#1]
In looking up the proof of the correspondence between compact Hausdorff topological spaces and commutative C^* algebras, I stumbled across the following StackExchange post:

https://math.stackexchange.com/questions/170984/are-commutative-c-algebras-really-dual-to-locally-compact-hausdorff-spaces

Is this a problem?

Unfortunately nLab is down right now so I can't check their statement.

**Comment by kim-em** [comment]
I think the assignment question (and the current version of nLab) is correct. I only asked the easier question about _compact_ Hausdorff spaces, while Qiaochu's question is about the locally compact case.

**Comment by khoek** [comment]
Thanks Scott!
