### ISSUE TITLE
Merging essays

### ISSUE THREAD

**Issue by khoek** [semorrison/category-theory-2018#2]
Hey Scott,

As Chris was asking Yiming if he could read her essay/for other references on Topos theory (and some other student topics too), Yossi suggested that (those of us who wish) should ask if we could host our final essays up here.

Would you be okay with that?

I thought if we sent pull-requests, then that could be considered personal permission.

**Comment by khoek** [comment]
Some students also expressed some anxiety with sending a pull request (e.g. not having a GitHub account), and asked if they could email you permission and have you upload it for them.

**Comment by kim-em** [comment]
Yes, either way is fine! Good suggestion.
